import type { Entity, EntityField, DatabaseRenderer } from "./types.js";

const MONGO_TYPE_MAP: Record<string, string> = {
  uuid: "UUID",
  timestamp: "Date",
  date: "Date",
  integer: "Int32",
  decimal: "Decimal128",
  float: "Double",
  boolean: "Bool",
  string: "String",
  i64_decicents: "Long",
};

const MONGOOSE_TS_TYPE_MAP: Record<string, string> = {
  uuid: "string",
  timestamp: "Date",
  date: "Date",
  integer: "number",
  decimal: "number",
  float: "number",
  boolean: "boolean",
  string: "string",
  i64_decicents: "number",
};

const MONGOOSE_SCHEMA_TYPE_MAP: Record<string, string> = {
  uuid: "String",
  timestamp: "Date",
  date: "Date",
  integer: "Number",
  decimal: "Decimal128",
  float: "Number",
  boolean: "Boolean",
  string: "String",
  i64_decicents: "Number",
};

function mongoType(field: EntityField): string {
  return MONGO_TYPE_MAP[field.type] || "String";
}

function mongooseTsType(field: EntityField): string {
  return MONGOOSE_TS_TYPE_MAP[field.type] || "string";
}

function mongooseSchemaType(field: EntityField): string {
  return MONGOOSE_SCHEMA_TYPE_MAP[field.type] || "String";
}

function mongoValidator(entity: Entity): string {
  const lines: string[] = [];
  lines.push(`  $jsonSchema: {`);
  lines.push(`    bsonType: "object",`);
  lines.push(`    required: [${entity.fields.filter((f) => !f.optional && !f.primaryKey).map((f) => `"${f.name}"`).join(", ")}],`);
  lines.push(`    properties: {`);

  for (let i = 0; i < entity.fields.length; i++) {
    const field = entity.fields[i];
    if (!field) continue;
    const mType = mongoType(field);
    const isLast = i === entity.fields.length - 1;
    const propLines: string[] = [];
    propLines.push(`      "${field.name}": {`);
    propLines.push(`        bsonType: "${mType.toLowerCase()}"`);
    if (field.primaryKey) {
      propLines.push(`        // auto-generated UUID typically set in application code`);
    }
    propLines.push(`      }${isLast ? "" : ","}`);
    lines.push(propLines.join("\n"));
  }

  // Foreign key references as suggested indexes
  if (entity.foreignKeys.length > 0) {
    lines.push(`    },`);
    lines.push(`    // Suggested indexes for FK references:`);
    for (const fk of entity.foreignKeys) {
      lines.push(`    // db.${entity.entity}.createIndex({ "${fk.field}": 1 });`);
    }
    lines.push(`  }`);
  } else {
    lines.push(`    }`);
  }

  return lines.join("\n");
}

export const mongoDbRenderer: DatabaseRenderer = {
  engine: "mongodb",

  mapType(field: EntityField): string {
    return mongoType(field);
  },

  generateCreateTable(entity: Entity): string {
    // For MongoDB, "CREATE TABLE" generates a collection with validation
    const lines: string[] = [];
    lines.push(`// Collection: ${entity.entity}`);
    lines.push(`db.createCollection("${entity.entity}", {`);
    lines.push(mongoValidator(entity));
    lines.push(`});`);

    // Compound indexes
    for (const fk of entity.foreignKeys) {
      lines.push(`db.${entity.entity}.createIndex({ "${fk.field}": 1 });`);
    }

    return lines.join("\n");
  },

  generateDDL(entities: Entity[], moduleName?: string): string {
    const filtered = moduleName
      ? entities.filter((e) => e.module === moduleName)
      : entities;

    const lines: string[] = [];
    lines.push(`// MongoDB Collection Definitions${moduleName ? ` for module: ${moduleName}` : ""}`);
    lines.push(`// Generated by Blueprint entity renderer`);
    lines.push(`// Entity count: ${filtered.length}`);
    lines.push("");

    // Sort: entities with no FK dependencies first (embedded refs)
    const ordered = [...filtered].sort((a, b) => {
      const aRefs = new Set(a.foreignKeys.map((fk) => fk.refEntity));
      const bRefs = new Set(b.foreignKeys.map((fk) => fk.refEntity));
      if (aRefs.has(b.entity)) return -1;
      if (bRefs.has(a.entity)) return 1;
      return 0;
    });

    for (const entity of ordered) {
      lines.push(this.generateCreateTable(entity));
      lines.push("");
    }

    return lines.join("\n");
  },
};

function toPascalCase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export function generateMongooseSchema(entities: Entity[], moduleName?: string): string {
  const filtered = moduleName
    ? entities.filter((e) => e.module === moduleName)
    : entities;

  const lines: string[] = [];
  lines.push("import mongoose, { Schema, Document } from 'mongoose';");
  lines.push("");

  for (const entity of filtered) {
    const entityName = toPascalCase(entity.entity);

    lines.push(`export interface I${entityName} {`);
    for (const field of entity.fields) {
      lines.push(`  ${field.name}${field.optional ? "?" : ""}: ${mongooseTsType(field)};`);
    }
    lines.push("}");
    lines.push("");

    const schemaName = `${entity.entity}Schema`;
    lines.push(`const ${schemaName} = new Schema<I${entityName}>({`);

    for (let i = 0; i < entity.fields.length; i++) {
      const field = entity.fields[i];
      if (!field) continue;
      const mType = mongooseSchemaType(field);
      const isLast = i === entity.fields.length - 1;
      const required = field.primaryKey || !field.optional;
      const comma = isLast && entity.foreignKeys.length === 0 ? "" : ",";
      lines.push(`  ${field.name}: { type: ${mType}, required: ${required} }${comma}`);
    }

    for (const [i, fk] of entity.foreignKeys.entries()) {
      const refName = toPascalCase(fk.refEntity);
      const isLast = i === entity.foreignKeys.length - 1;
      lines.push(`  ${fk.field}: { type: Schema.Types.ObjectId, ref: '${refName}' }${isLast ? "" : ","}`);
    }

    lines.push(`}, { timestamps: true });`);
    lines.push("");

    lines.push(`export const ${entityName}Model = mongoose.model<I${entityName}>('${entityName}', ${schemaName});`);
    lines.push("");
  }

  return lines.join("\n");
}
