import type { Entity, EntityField, DatabaseRenderer } from "./types.js";

const MONGO_TYPE_MAP: Record<string, string> = {
  uuid: "UUID",
  timestamp: "Date",
  date: "Date",
  integer: "Int32",
  decimal: "Decimal128",
  float: "Double",
  boolean: "Bool",
  string: "String",
  i64_decicents: "Long",
};

function mongoType(field: EntityField): string {
  return MONGO_TYPE_MAP[field.type] || "String";
}

function mongoValidator(entity: Entity): string {
  const lines: string[] = [];
  lines.push(`  $jsonSchema: {`);
  lines.push(`    bsonType: "object",`);
  lines.push(`    required: [${entity.fields.filter((f) => !f.optional && !f.primaryKey).map((f) => `"${f.name}"`).join(", ")}],`);
  lines.push(`    properties: {`);

  for (let i = 0; i < entity.fields.length; i++) {
    const field = entity.fields[i];
    if (!field) continue;
    const mType = mongoType(field);
    const isLast = i === entity.fields.length - 1;
    const propLines: string[] = [];
    propLines.push(`      "${field.name}": {`);
    propLines.push(`        bsonType: "${mType.toLowerCase()}"`);
    if (field.primaryKey) {
      propLines.push(`        // auto-generated UUID typically set in application code`);
    }
    propLines.push(`      }${isLast ? "" : ","}`);
    lines.push(propLines.join("\n"));
  }

  // Foreign key references as suggested indexes
  if (entity.foreignKeys.length > 0) {
    lines.push(`    },`);
    lines.push(`    // Suggested indexes for FK references:`);
    for (const fk of entity.foreignKeys) {
      lines.push(`    // db.${entity.entity}.createIndex({ "${fk.field}": 1 });`);
    }
    lines.push(`  }`);
  } else {
    lines.push(`    }`);
  }

  return lines.join("\n");
}

export const mongoDbRenderer: DatabaseRenderer = {
  engine: "mongodb",

  mapType(field: EntityField): string {
    return mongoType(field);
  },

  generateCreateTable(entity: Entity): string {
    // For MongoDB, "CREATE TABLE" generates a collection with validation
    const lines: string[] = [];
    lines.push(`// Collection: ${entity.entity}`);
    lines.push(`db.createCollection("${entity.entity}", {`);
    lines.push(mongoValidator(entity));
    lines.push(`});`);

    // Compound indexes
    for (const fk of entity.foreignKeys) {
      lines.push(`db.${entity.entity}.createIndex({ "${fk.field}": 1 });`);
    }

    return lines.join("\n");
  },

  generateDDL(entities: Entity[], moduleName?: string): string {
    const filtered = moduleName
      ? entities.filter((e) => e.module === moduleName)
      : entities;

    const lines: string[] = [];
    lines.push(`// MongoDB Collection Definitions${moduleName ? ` for module: ${moduleName}` : ""}`);
    lines.push(`// Generated by Blueprint entity renderer`);
    lines.push(`// Entity count: ${filtered.length}`);
    lines.push("");

    // Sort: entities with no FK dependencies first (embedded refs)
    const ordered = [...filtered].sort((a, b) => {
      const aRefs = new Set(a.foreignKeys.map((fk) => fk.refEntity));
      const bRefs = new Set(b.foreignKeys.map((fk) => fk.refEntity));
      if (aRefs.has(b.entity)) return -1;
      if (bRefs.has(a.entity)) return 1;
      return 0;
    });

    for (const entity of ordered) {
      lines.push(this.generateCreateTable(entity));
      lines.push("");
    }

    return lines.join("\n");
  },
};
