import type { Entity, EntityField, DatabaseRenderer } from "./types.js";

const SQLITE_TYPE_MAP: Record<string, string> = {
  uuid: "TEXT",
  timestamp: "TEXT",
  date: "TEXT",
  integer: "INTEGER",
  decimal: "REAL",
  float: "REAL",
  boolean: "INTEGER",
  string: "TEXT",
  i64_decicents: "INTEGER",
};

function sqliteType(field: EntityField): string {
  return SQLITE_TYPE_MAP[field.type] || "TEXT";
}

function sqliteColumnDef(field: EntityField): string {
  const base = sqliteType(field);
  const parts = [`  "${field.name}" ${base}`];
  if (field.primaryKey) parts.push("PRIMARY KEY");
  if (!field.optional && !field.primaryKey) parts.push("NOT NULL");
  if (field.primaryKey) parts.push("DEFAULT (lower(hex(randomblob(16))))");
  return parts.join(" ");
}

export const sqliteRenderer: DatabaseRenderer = {
  engine: "sqlite",

  mapType(field: EntityField): string {
    return sqliteType(field);
  },

  generateCreateTable(entity: Entity): string {
    const lines: string[] = [];
    lines.push(`CREATE TABLE "${entity.entity}" (`);

    const colDefs = entity.fields.map(sqliteColumnDef);
    for (const fk of entity.foreignKeys) {
      const refField = entity.fields.find((f) => f.name === fk.field);
      if (refField) {
        colDefs.push(
          `  CONSTRAINT "fk_${entity.entity}_${fk.field}" FOREIGN KEY ("${fk.field}") REFERENCES "${fk.refEntity}"("id")`,
        );
      }
    }

    lines.push(colDefs.join(",\n"));
    lines.push(");\n");

    for (const fk of entity.foreignKeys) {
      lines.push(`CREATE INDEX "idx_${entity.entity}_${fk.field}" ON "${entity.entity}" ("${fk.field}");`);
    }

    return lines.join("\n");
  },

  generateDDL(entities: Entity[], moduleName?: string): string {
    const filtered = moduleName
      ? entities.filter((e) => e.module === moduleName)
      : entities;

    const lines: string[] = [];
    lines.push(`-- SQLite DDL${moduleName ? ` for module: ${moduleName}` : ""}`);
    lines.push(`-- Generated by Blueprint entity renderer`);
    lines.push(`-- Entity count: ${filtered.length}`);
    lines.push("");

    const ordered = [...filtered].sort((a, b) => {
      const aRefs = new Set(a.foreignKeys.map((fk) => fk.refEntity));
      const bRefs = new Set(b.foreignKeys.map((fk) => fk.refEntity));
      if (aRefs.has(b.entity)) return -1;
      if (bRefs.has(a.entity)) return 1;
      return 0;
    });

    for (const entity of ordered) {
      lines.push(this.generateCreateTable(entity));
    }

    return lines.join("\n");
  },
};
