import type { Entity, EntityField, DatabaseRenderer } from "./types.js";

const TIMESCALE_TYPE_MAP: Record<string, string> = {
  uuid: "UUID",
  timestamp: "TIMESTAMPTZ",
  date: "DATE",
  integer: "INTEGER",
  decimal: "DECIMAL(12,4)",
  float: "DOUBLE PRECISION",
  boolean: "BOOLEAN",
  string: "TEXT",
  i64_decicents: "BIGINT",
};

function tsType(field: EntityField): string {
  return TIMESCALE_TYPE_MAP[field.type] || "TEXT";
}

function tsColumnDef(field: EntityField): string {
  const base = tsType(field);
  const parts = [`  "${field.name}" ${base}`];
  if (field.primaryKey) parts.push("PRIMARY KEY");
  if (!field.optional && !field.primaryKey) parts.push("NOT NULL");
  if (field.primaryKey) parts.push("DEFAULT gen_random_uuid()");
  return parts.join(" ");
}

function hasTimeField(entity: Entity): EntityField | undefined {
  return entity.fields.find(
    (f) => f.type === "timestamp" || f.type === "date" || f.name.endsWith("_at"),
  );
}

export const timescaledbRenderer: DatabaseRenderer = {
  engine: "timescaledb",

  mapType(field: EntityField): string {
    return tsType(field);
  },

  generateCreateTable(entity: Entity): string {
    const lines: string[] = [];
    lines.push(`CREATE TABLE "${entity.entity}" (`);

    const colDefs = entity.fields.map(tsColumnDef);
    for (const fk of entity.foreignKeys) {
      const refField = entity.fields.find((f) => f.name === fk.field);
      if (refField) {
        colDefs.push(
          `  CONSTRAINT "fk_${entity.entity}_${fk.field}" FOREIGN KEY ("${fk.field}") REFERENCES "${fk.refEntity}"("id")`,
        );
      }
    }

    lines.push(colDefs.join(",\n"));
    lines.push(");\n");

    // Convert to hypertable
    const timeField = hasTimeField(entity);
    if (timeField) {
      lines.push(
        `SELECT create_hypertable('${entity.entity}', '${timeField.name}', if_not_exists => TRUE);`,
      );
    } else {
      lines.push(
        `-- WARNING: No time column found for hypertable creation on ${entity.entity}.`,
      );
      lines.push(
        `-- Add a TIMESTAMP/TIMESTAMPTZ column or use add_dimension() for space partitioning.`,
      );
    }

    // Compression policy
    if (timeField) {
      lines.push(
        `ALTER TABLE "${entity.entity}" SET (timescaledb.compress, timescaledb.compress_segmentby = '"${entity.entity}.id"');`,
      );
      lines.push(
        `SELECT add_compression_policy('${entity.entity}', INTERVAL '7 days', if_not_exists => TRUE);`,
      );
    }

    // Index on foreign keys
    for (const fk of entity.foreignKeys) {
      lines.push(`CREATE INDEX "idx_${entity.entity}_${fk.field}" ON "${entity.entity}" ("${fk.field}");`);
    }

    return lines.join("\n");
  },

  generateDDL(entities: Entity[], moduleName?: string): string {
    const filtered = moduleName
      ? entities.filter((e) => e.module === moduleName)
      : entities;

    const lines: string[] = [];
    lines.push(`-- TimescaleDB DDL${moduleName ? ` for module: ${moduleName}` : ""}`);
    lines.push(`-- Generated by Blueprint entity renderer`);
    lines.push(`-- Requires: CREATE EXTENSION IF NOT EXISTS timescaledb;`);
    lines.push(`-- Entity count: ${filtered.length}`);
    lines.push("");

    const ordered = [...filtered].sort((a, b) => {
      const aRefs = new Set(a.foreignKeys.map((fk) => fk.refEntity));
      const bRefs = new Set(b.foreignKeys.map((fk) => fk.refEntity));
      if (aRefs.has(b.entity)) return -1;
      if (bRefs.has(a.entity)) return 1;
      return 0;
    });

    for (const entity of ordered) {
      lines.push(this.generateCreateTable(entity));
    }

    return lines.join("\n");
  },
};
