import { 
  ExtractionOutput, DecompositionOutput, AdversarialReport, 
  DesignOutput, VerificationOutput 
} from "./schemas";
import { ScaffoldFile } from "./scaffolder";

/**
 * Deterministic markdown assembly. 
 * NO LLM INVOLVEMENT. This prevents hallucination in the final spec.
 */
export function assembleSpec(
  prompt: string,
  extraction: ExtractionOutput,
  decomposition: DecompositionOutput,
  adversarial: AdversarialReport,
  design: DesignOutput,
  verification: VerificationOutput,
  scaffoldFiles: ScaffoldFile[] = []
): string {
  const date = new Date().toISOString().split("T")[0];
  
  let md = `# Engineering Specification — Automated System Design
> Generated by Engineering Blueprinter | Fintech Domain
> Formal Verification: ${verification.overall_status} | ${date}

## 1. Requirements
### 1.1 Functional Requirements
${extraction.functional_requirements.map(fr => `- **${fr.id}**: ${fr.statement} (${fr.priority})`).join("\n")}

### 1.2 Non-Functional Requirements
${extraction.non_functional_requirements.map(nfr => `- **${nfr.id}**: ${nfr.constraint}: ${nfr.value}`).join("\n")}

### 1.3 Implicit Constraints (Auto-Applied)
${extraction.implicit_constraints.map(c => `- ${c}`).join("\n")}

## 2. Assumptions
${extraction.assumptions.map(a => `- **${a.id}**: ${a.statement}\n  *Impact*: ${a.impact}`).join("\n")}

## 3. Failure Mode Register
${adversarial.matched_failure_modes.map(fm => `
### ${fm.failure_mode_id}: Affected ${fm.affected_service}
- **Operation**: ${fm.affected_operation ?? "N/A"}
- **Likelihood**: ${fm.likelihood} | **Severity**: ${fm.severity}
- **Consequence**: ${fm.observable_consequence ?? "N/A"}
- **Sequence**:
${(fm.failure_sequence ?? []).map(s => `  ${s}`).join("\n")}
`).join("\n")}

## 4. Domain Decomposition
### 4.1 Services
${decomposition.services.map(s => `- **${s.name}** (${s.id})
  *Owns*: ${s.owns.join(", ")}
  *Reads From*: ${s.reads_from.join(", ")}`).join("\n")}

### 4.2 Interactions
**Synchronous**:
${decomposition.sync_interactions.map(i => `- ${i.caller} → ${i.callee}: ${i.purpose} (SLA: ${i.sla_ms}ms)`).join("\n")}

**Asynchronous**:
${decomposition.async_interactions.map(i => `- ${i.publisher} publishes \`${i.event}\` to ${i.consumers?.join(", ")}`).join("\n")}

## 5. Algorithms
${design.algorithms.map(alg => `
### ${alg.operation} (${alg.service})
**Preconditions**: ${alg.preconditions.join(", ") || "None"}
**Steps**:
${alg.steps.map(s => `${s.number}. ${s.description} [${s.execution}]${s.can_fail ? ` (Can fail: ${s.failure_handling})` : ""}`).join("\n")}
**Postconditions**: ${alg.postconditions.join(", ") || "None"}
`).join("\n")}

## 6. Invariants
${verification.models.flatMap(m => m.verified_invariants).map(inv => `- **${inv.id}**: ${inv.statement}
  *TLA+*: \`${inv.formal_assertion}\`
  *Status*: ${inv.verified ? "✅ VERIFIED" : "❌ VIOLATED"} (${inv.verification_bound ?? "No bound"})`).join("\n")}

## 7. Formal Model
${verification.models.map(m => `
### Model: ${m.model_id}
Status: ${m.status}
Bounds: ${JSON.stringify(m.verification_bounds)}
Duration: ${m.duration_ms}ms
`).join("\n")}

## 8. Implementation Order
1. Shared infrastructure (database schema, idempotency store).
${decomposition.services.map((s, i) => `${i + 2}. Service: ${s.name} (${s.id})`).join("\n")}
${decomposition.services.length + 2}. Integration layer and end-to-end tests.

## 9. Code Scaffold
${scaffoldFiles.length > 0 ? scaffoldFiles.map(f => `
### \`${f.path}\`
\`\`\`typescript
${f.content}
\`\`\`
`).join("\n") : "Not requested."}
`;

  return md;
}
